overlay = "."
uploaders = ["Matthias Geiger <werdahias@debian.org>"]
collapse_features = true

[source]
build_depends = ["gir-rust-code-generator (>= 0.20)", "libgirepository1.0-dev", "xmlstarlet"]

[packages.lib]
test_is_broken = false
depends = ["libglib2.0-dev (>= 2.80)"]

[packages."lib+compiletests"]
test_is_broken = true
